### PR TITLE
feat: Add on-call policy

### PR DESCRIPTION
**Pull request by minikin**
- add  on call policy

### CODE REVIEW

**Review by stevenj — APPROVED** [review]
LGTM.
The only comment I have is Response/Resolution only deals with Response, which I take to mean the first action taken after the alert.

We should have something also relating to desired resolution time windows as well.  

It's not always feasible to resolve an issue in the desired time frame, but I think it's good to lay out a reasonable expectation, and perhaps what escalation looks like if it can't be resolved in the time frame.

**Comment by minikin** [comment]
@stevenj Thank you for your feedback. I added [Resolution Times](https://github.com/input-output-hk/catalyst-engineering/pull/11/commits/3fec50917711989ae4207189a8cbc526847d2dbe) section.

**Review by saibatizoku — APPROVED** [review]
LGTM. I would only suggest verifying that On-Call personel have the necessary permissions and locations of the services that might need inspection.

**Review by kukkok3 — COMMENTED** [review]
LGTM

**Pull request merged**
